### ISSUE TITLE
[3.5] Could not get token for bulk insert on BulkInsert even with anonymous access

### ISSUE THREAD

**Issue by danielmarbach** [ravendb/ravendb#11108]
One of our clients is getting

```
Exception:
Could not get token for bulk insert
StackTrace:
   at Raven.Client.Document.RemoteBulkInsertOperation.<StartBulkInsertAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.RemoteBulkInsertOperation.<DisposeAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.ChunkedRemoteBulkInsertOperation.<DisposeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Auditing.AuditPersister.<Persist>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Auditing.AuditIngestionComponent.<<-ctor>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__29.MoveNext()
Source:
Raven.Client.Lightweight
TargetSite:
Void MoveNext()
A task was canceled.
Data :System.Collections.DictionaryEntry
StackTrace:
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<>c__DisplayClass36_0.<<SendRequestInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<RunWithAuthRetry>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<ReadResponseJsonAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.RemoteBulkInsertOperation.<GetAuthToken>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.RemoteBulkInsertOperation.<GetToken>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.RemoteBulkInsertOperation.<StartBulkInsertAsync>d__23.MoveNext()
Source:
Raven.Client.Lightweight
TargetSite:
Void MoveNext()
A task was canceled.
StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<>c__DisplayClass36_0.<<SendRequestInternal>b__0>d.MoveNext()
Source:
mscorlib
TargetSite:
Void ThrowForNonSuccess(System.Threading.Tasks.Task)
```

which seems to indicate that the GetToken call did fail

https://github.com/ravendb/ravendb/blob/v3.5/Raven.Client.Lightweight/Document/RemoteBulkInsertOperation.cs#L119

but we are using Anonymous access. Why should this fail?

**Comment by danielmarbach** [comment]
Pretty wild guess but could it be related to https://github.com/ravendb/ravendb/pull/11110?

**Comment by arekpalinski** [comment]
It doesn't seems to be related because in https://github.com/ravendb/ravendb/pull/11110 you fixed potential deadlock while here `A task was canceled.` was thrown under the covers.

It looks that the client wasn't able to reach the server within the default `HttpClient` timeout (100 sec) what results in `A task was canceled.`.

How is your client hosting RavenDB? Are they sure the server was up at the time they got this error?

**Comment by danielmarbach** [comment]
@arekpalinski we use embedded RavenDB and the client is part of the same AppDomain. So we are in total charge of the whole stack. So the server not being up and running would mean our entire process would have crashed. The only thing I can see is that we somehow exhaust the service connection limit but we set that to 100 and I'm pretty sure we are not exceeding that (as far as I understand RavenDB client also caches the clients and therefore connections)

**Comment by arekpalinski** [comment]
Yes, RavenDB caches `HttpClient` instances under the covers.

**Comment by danielmarbach** [comment]
I was thinking it might be related because when the deadlock happens couldn't we basically stall totally the operations on the bulk insert and those run into blocking HTTP client operations as well (since those things are coupled together)?

From our perspective we have only a few bulk insertion operations happening concurrently and given RavenDB caches the client I`m not seeing yet why things should get stalled that much to run into the 100 seconds HTTP client timeout.

**Comment by arekpalinski** [comment]
Your PRs got merged. We'll run the full test suit. Once it passes I will let you know when new build is out.

**Comment by arekpalinski** [comment]
@danielmarbach Just letting you know that we released `3.5.10-patch-35302` which includes your fixes.

**Comment by danielmarbach** [comment]
While it seems that some of the improvements I've contributed make this less likely we still see from time to time this issue occurring with customers. I've raised another round of PRs. Namely #11508 #11509 and #11510

Is it also possible that due to pooling we might end up pooling a faulty HTTP client and on subsequent reuse it is no longer possible to acquire the token?

**Comment by ayende** [comment]
I don't think that this is likely. We are handling retiring of old clients ourselves here:
https://github.com/ravendb/ravendb/blob/v3.5/Raven.Client.Lightweight/Util/HttpClientCache.cs

**Comment by danielmarbach** [comment]
It's very strange. We still see the token problem from time to time even under very moderate load. I'm trying to decipher how that can happen because in the scenarios if seen the documents are really small and only a few.

**Comment by danielmarbach** [comment]
Yeah I came to the same conclusion when I checked the cache

**Comment by danielmarbach** [comment]
We got our hands on a dump from a customer and it looks like the unable to get the token is closely related to RavenDB even though embedded being somehow in a complete locked state so that it cannot even accept requests anymore.

![image](https://user-images.githubusercontent.com/174258/101659752-b09af880-3a46-11eb-88ad-acaf5c789222.png)

Is there a way to disable the replication and cluster topology checks? 

I saw there is quite a bit of locking and sync over async in combination with Lazy and concurrency going on in this path that makes us wonder if we are running in into a deadlock scenario. How can embedded instances running in the same process end up in an unavailable state?

**Comment by danielmarbach** [comment]
Another thing that seems to be closely related to RavenDB not being able to do anything anymore is the following

```
2020-11-15 20:47:27.0846|313|Warn|Raven.Client.Connection.Async.AsyncServerClient|Was unable to fetch topology from primary node http://localhost also there is no cached topology
2020-11-15 20:55:46.6078|145|Warn|Raven.Client.Connection.Async.AsyncServerClient|Was unable to fetch topology from primary node http://localhost also there is no cached topology
2020-11-15 20:57:26.6249|145|Error|Raven.Client.Connection.ReplicationInformerBase`1|Could not contact master for new replication information
Raven.Abstractions.Connection.ErrorResponseException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<>c__DisplayClass36_0.<<SendRequestInternal>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<>c__DisplayClass36_0.<<SendRequestInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<RunWithAuthRetry>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<ReadResponseJsonAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Async.AsyncServerClient.<DirectGetReplicationDestinationsAsync>d__185.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Abstractions.Util.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Abstractions.Util.AsyncHelpers.RunSync[T](Func`1 task)
   at Raven.Client.Connection.ReplicationInformer.RefreshReplicationInformationInternal(String url, Func`1 getReplicationDestinations)
```

@ayende @arekpalinski Any thoughts? The issue is definitely not resolved. 

Can you guys please help to better understand this situation?
